package com.hibox.carclient.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

/**
 * Everyday is another day, keep going.
 * Created by Ramo
 * email:   327300401@qq.com
 * date:    2018/09/20 15:12
 * desc:
 */


public class CarModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.id
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.plate_number
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private String plateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.section_number
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private String sectionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.status
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.create_time
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.start_time
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")

    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.end_time
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")

    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.image1
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private String image1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.image2
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private String image2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.image3
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private String image3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column illegal_stop.description
     *
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.id
     *
     * @return the value of illegal_stop.id
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.id
     *
     * @param id the value for illegal_stop.id
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.plate_number
     *
     * @return the value of illegal_stop.plate_number
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public String getPlateNumber() {
        return plateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.plate_number
     *
     * @param plateNumber the value for illegal_stop.plate_number
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber == null ? null : plateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.section_number
     *
     * @return the value of illegal_stop.section_number
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public String getSectionNumber() {
        return sectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.section_number
     *
     * @param sectionNumber the value for illegal_stop.section_number
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setSectionNumber(String sectionNumber) {
        this.sectionNumber = sectionNumber == null ? null : sectionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.status
     *
     * @return the value of illegal_stop.status
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.status
     *
     * @param status the value for illegal_stop.status
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.create_time
     *
     * @return the value of illegal_stop.create_time
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.create_time
     *
     * @param createTime the value for illegal_stop.create_time
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.start_time
     *
     * @return the value of illegal_stop.start_time
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.start_time
     *
     * @param startTime the value for illegal_stop.start_time
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.end_time
     *
     * @return the value of illegal_stop.end_time
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.end_time
     *
     * @param endTime the value for illegal_stop.end_time
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.image1
     *
     * @return the value of illegal_stop.image1
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public String getImage1() {
        return image1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.image1
     *
     * @param image1 the value for illegal_stop.image1
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setImage1(String image1) {
        this.image1 = image1 == null ? null : image1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.image2
     *
     * @return the value of illegal_stop.image2
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.image2
     *
     * @param image2 the value for illegal_stop.image2
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setImage2(String image2) {
        this.image2 = image2 == null ? null : image2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.image3
     *
     * @return the value of illegal_stop.image3
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public String getImage3() {
        return image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.image3
     *
     * @param image3 the value for illegal_stop.image3
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setImage3(String image3) {
        this.image3 = image3 == null ? null : image3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column illegal_stop.description
     *
     * @return the value of illegal_stop.description
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column illegal_stop.description
     *
     * @param description the value for illegal_stop.description
     * @mbggenerated Wed Sep 19 20:24:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

}